# Generated by Django 4.1.7 on 2023-03-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='tblemployee',
        ),
    ]
